application: booming-crowbar-88618
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

pagespeed:
 domains_to_rewrite:
  - booming-crowbar-88618.appspot.com
 enabled_rewriters:
  - MinifyCss