application: carbon-gecko-88803
version: 1
runtime: go
api_version: go1

default_expiration: "5d"

handlers:
- url: /.*
  script: _go_app
  login: required

pagespeed:
 domains_to_rewrite:
  - carbon-gecko-88803.appspot.com
 enabled_rewriters:
  - MinifyCss