application: carbon-gecko-88803
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

pagespeed:
 domains_to_rewrite:
  - carbon-gecko-88803.appspot.com
 enabled_rewriters:
  - MinifyCss